version: '3'

services:
  nginx:
      build: ./nginx/
      ports:
        - 80:80
        - 443:443
      links:
        - php
      volumes:
        - ./www:/var/www/html
      restart: always

  php:
      build: ./php/
      expose:
        - 9000
      volumes:
        - ./www:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - ./php/www.conf:/usr/local/etc/php/fpm/pool.d/www.conf
      links:
        - db
      env_file:
        - ./www/.env
      restart: always
      
  db:
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=housekeeping
      volumes:
        - ./database:/var/lib/mysql
      ports:
        - 3306:3306
